server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8087
          predicates:
            - Path=/auth/**

        - id: bus-service
          uri: http://localhost:8082
          predicates:
            - Path=/buses/**

        - id: student-service
          uri: http://localhost:8083
          predicates:
            - Path=/students/**

        - id: location-service
          uri: http://localhost:8085
          predicates:
            - Path=/locations/**

        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/notifications/**

        - id: planning-service
          uri: http://localhost:8088
          predicates:
            - Path=/routes/**

        - id: group-service
          uri: http://localhost:8084
          predicates:
            - Path=/groups/**
